version: '3.3'

services:
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: product_challenge
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database/custom.cnf:/etc/mysql/conf.d/custom.cnf

  adminer:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      PMA_ARBITRARY: 1
    links:
      - database

  product-core:
    build:
      context: ./product-core
      dockerfile: Dockerfile
    container_name: core_container
    ports:
      - "4040:4040"
    depends_on:
      - database

  product-web:
    build:
      context: ./product-web
      dockerfile: Dockerfile
    container_name: web_container
    ports:
      - "5050:80"
    links:
      - product-core